<?php

namespace Database\Factories;

use App\Models\Media;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * Media factory (03-technical-specs/03-database-schema.md §2 +
 * 09-media-pipeline.md). `collection_name` is included so inserts pass
 * the NOT NULL column; `uuid` is generated by the Spatie HasUuid
 * creating hook inherited by App\Models\Media.
 *
 * Alt text is REQUIRED — 03-technical-specs/13-testing-qa.md §6 "every
 * fixture media ships alt text" — so the a11y gate passes on seeded
 * pages too. The underlying model (User here) is a factory default;
 * pass ->for(...) / override model_id when a specific owner matters.
 */
class MediaFactory extends Factory
{
    protected $model = Media::class;

    public function definition(): array
    {
        return [
            // Morph target defaults to a user avatar; override for content media.
            'model_type' => 'App\Models\User',
            'model_id' => User::factory(),
            'collection_name' => 'default',
            'name' => fake()->words(3, true),
            'file_name' => fake()->unique()->lexify('??????').'.jpg',
            'mime_type' => 'image/jpeg',
            'disk' => 'public',
            'conversions_disk' => 'public',
            'size' => fake()->numberBetween(50_000, 800_000),
            // Alt text required — never null/empty for non-decorative fixtures.
            'alt_text' => fake()->sentence(6),
            'is_decorative' => false,
            'namespace' => fake()->randomElement(config('sewa.media.namespaces')),
            'manipulations' => [],
            'custom_properties' => [],
            'generated_conversions' => [],
            'responsive_images' => [],
        ];
    }
}
