{{-- ops.digest — daily 09:00 rhythm (10-email §4): leads, SLA breaches,
     failed jobs, queue depth, zero-result searches. --}}
@extends('mail.shared.layout')

@section('body')
    <p style="margin:0 0 14px; font-size:17px; font-weight:600;">Daily ops digest</p>

    <ul style="margin:0 0 16px; padding-left:18px;">
        @foreach ($lines as $line)
            <li style="margin-bottom:6px;">{{ $line }}</li>
        @endforeach
    </ul>

    <table role="presentation" cellpadding="0" cellspacing="0" style="width:100%; font-size:14px;">
        @foreach ($sections as $label => $summary)
            <tr>
                <td style="padding:6px 0; border-bottom:1px solid #E8E1D5; color:#8A7F6E; width:40%;">{{ $label }}</td>
                <td style="padding:6px 0; border-bottom:1px solid #E8E1D5;">{{ $summary }}</td>
            </tr>
        @endforeach
    </table>
@endsection

@section('footer_note')
    Generated by ops:digest · schedule 09:00 IST · 04-modules/03-leads-crm §4.4.
@endsection
