{{-- Shared email layout (03-technical-specs/10-email.md §1.3): brand
     header + one body + brand footer, table-based and email-client-safe,
     plain-text alternative auto-generated by the mailer. Locale variants
     ride the I18n module (M6) — authored EN-first. --}}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@yield('subject', 'Sewa Hospitality')</title>
</head>
<body style="margin:0; padding:0; background-color:#FAF7F2; font-family:-apple-system,'Segoe UI',Roboto,Helvetica,Arial,sans-serif; color:#26201A;">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#FAF7F2;">
        <tr>
            <td align="center" style="padding:24px 12px;">
                <table role="presentation" width="600" cellpadding="0" cellspacing="0" style="max-width:600px; width:100%; background-color:#ffffff; border:1px solid #E8E1D5; border-radius:12px;">

                    {{-- Brand header --}}
                    <tr>
                        <td style="padding:24px 32px 16px; border-bottom:2px solid #0E7C66;">
                            <span style="font-size:18px; font-weight:700; letter-spacing:0.08em; color:#0E7C66;">SEWA HOSPITALITY</span>
                            <span style="display:block; font-size:12px; color:#8A7F6E; margin-top:2px;">Care, delivered.</span>
                        </td>
                    </tr>

                    {{-- Body --}}
                    <tr>
                        <td style="padding:28px 32px 8px; font-size:15px; line-height:1.65;">
                            @yield('body')
                        </td>
                    </tr>

                    {{-- One primary CTA --}}
                    @hasSection('cta')
                        <tr>
                            <td style="padding:16px 32px 24px;">
                                @yield('cta')
                            </td>
                        </tr>
                    @endif

                    {{-- Footer — NAP single-source --}}
                    <tr>
                        <td style="padding:16px 32px 28px; border-top:1px solid #E8E1D5; font-size:12px; line-height:1.6; color:#8A7F6E;">
                            <p style="margin:0 0 6px;">Sewa Hospitality Services Pvt. Ltd. · 2nd Floor, DT Mega Mall, A Block, DLF Phase 1, Gurugram, Haryana 122002, India</p>
                            <p style="margin:0 0 6px;"><a href="tel:+919873255531" style="color:#0E7C66; text-decoration:none;">+91 98732 55531</a> · <a href="https://sewahospitality.com" style="color:#0E7C66; text-decoration:none;">sewahospitality.com</a></p>
                            <p style="margin:0;">@yield('footer_note', 'You are receiving this email as part of your relationship with Sewa Hospitality.')</p>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</body>
</html>
